name: CI Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint Code
        run: flake8 app/ --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run Tests
        run: pytest

  deploy:
    name: Deploy to VM
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - name: SSH & Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/python-backend-app
            git pull origin main
            pip3 install --user -r requirements.txt
            pkill -f "python3 app/main.py" || true
            nohup python3 app/main.py > app.log 2>&1 &

  notify:
    name: Dummy Notify (No-Op)
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Placeholder Notify Step
        run: echo "Notify block (no-op). No notification sent."

