name: Notify Webhook

on:
  workflow_call:
    inputs:
      status:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Webhook Notification
        run: |
          curl -X POST ${{ secrets.WEBHOOK_URL }} \
          -H "Content-Type: application/json" \
          -d '{
            "pipeline": "CI/CD Pipeline",
            "status": "${{ inputs.status }}",
            "environment": "${{ inputs.environment }}",
            "timestamp": "'"$(date --utc +%FT%TZ)"'"
          }'

