name: Notify Webhook

on:
  workflow_call:
    inputs:
      status:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification to Webhook.site
        run: |
          curl -X POST ${{ secrets.WEBHOOK_URL }} \
          -H "Content-Type: application/json" \
          -d '{
                "status": "${{ inputs.status }}",
                "environment": "${{ inputs.environment }}",
                "repository": "${{ github.repository }}",
                "commit": "${{ github.sha }}",
                "triggered_by": "${{ github.actor }}",
                "workflow": "${{ github.workflow }}",
                "job": "${{ github.job }}",
                "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
              }'

