name: Notify Webhook

on:
  workflow_call:
    inputs:
      status:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification to Webhook
        run: |
          curl -X POST ${{ secrets.WEBHOOK_URL }} \
            -H "Content-Type: application/json" \
            -d '{
              "status": "${{ inputs.status }}",
              "environment": "${{ inputs.environment }}",
              "repository": "${{ github.repository }}",
              "run_id": "${{ github.run_id }}",
              "url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }'

